version: '2'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=mustafa_single_broker
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=PLAINTEXT://127.0.0.1:9092

#docker-compose up -d kafka-ui