version: "3"
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - "kafka_data:/mustafakafka"
    environment:
      - KAFKA_ENABLE_KRAFT=yes # new KRaft mode enabled.
      - KAFKA_CFG_PROCESS_ROLES=broker,controller #
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER #
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT #
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9094,CLIENT://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://127.0.0.1:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT #
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9094 #
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  kafka_data:
    driver: local

#docker-compose up -d