apiVersion: v1
kind: Pod 
metadata:
  name: postgres-pod-2
  labels:
    app: postgres-2
spec:
  containers:
  - name: postgres
    image: postgres:13
    ports:
    - containerPort: 5432 # containerın içinde koştuğu uygulama podu
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: mysecretpassword
    - name: POSTGRES_DB
      value: mydb
